language: node_js
node_js: '10'
branches:
  only: master
before_install: 
cache:
  directories: node_modules
install: npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$aaa"
  keep_history: true
  local_dir: "./dist"
  on:
    branch: master
env:
  global:
    secure: RjYt/9vUZuKvMOATUUZ1N7HFVK9Vl43BD7CIwCtLK7/NfHygkWkmz54CgyiDgLQvQlQuItuVPaHLkxFb7KPw8yALcpZjK78uiWpZcuP3bahtu02+DxROsMkoAYvamOwwbZfmdawmq9VdjgoN1ZtjPmkiyO449h6YCJDfq3Tq8FoDktK4mN1QKmExpQiQPs7cgErjav8EoLd7Wvz/YFSclocJL9XCetTBQ0FvTP5TVegkhRN47ikfprCI6dweAlaqGpc5YuLu4pi1ZFDq/munm4hX2kNctF+agSuPnwkHXbD29ZA61VXmjhhetWaC0oosjXJST9RB1Yw84oNvoNO97aPotUlf8+dw8X8U1zGiq0+tLRYMxe6bnpWEUnnB1B6daTKnQLXCpL4344EY2CPX4+cJvqst4vnh81tPv0jtW4QW6fSdcknaFKDJW1nTNM0Wh0iOeElVK6CCCPW3d2mNJd5qnfcPlql4Lbc5PrTW4ik6U1qqEi2GOIgn/U0ukCMUnWWCCTpFV6FljcUme0pY5WCwyN5TOm7wFbmFNAZF2YIqL/o870xrm4UTpl5P5d5k0duAhLrBfdcNN8qRKRQFTCVjumcUsrkASjL3zYtMsVTFLMY/R9NX8OqNRsUZCzki2VfSK/OyxRy/6MQ5DUdpD3yuV4T8xtDdc0OJKbghs0s=
  matrix:
    secure: Ne5VxATywwOLl1euqg2bih1PGe/EfFU1FX48sM+0LDm2pZfuo7ex254yc06vt+RRh1tg+8qBiiYq/Oc/wT/kT/xsNx/h9LKTI/mJK5qJd5ELjRyW+m9mZqtlJZaRvOvdfYbdrgwdM8uL3HtIS9NZ59akpUctF+JETITuy4lJ1XLfolaaER6FSM38OIsBM60vkqX+wyVkkBthSp+vxuQZ96u7I9XdadwBk40bf+d6GtW+utQWdwe5aIX6dpcl9t6ulNyfPhEIeQo/W+pXeB/6xLGulJ+scgqbXpIc3IXhxdu8WFq9k1Rgn4nIgOXLvSQ5ak7UO55GC8Q00tArTtQ6c1wUUyL1c6nTd1VSLicCf7WYhyLyALOHrch9sZQUJPifABdst976hcXzEVF18QdsESwhDqZarJqxPivYe2ZFL7PIbINlSg3wGNEuesPvWUqai2Ys7NlSSi9zuhAmFtqCiGTV2UW4/JyB3YkIXY+sbCffi/T/N7i7dpxE00K0Gd1UWkXcUJvNrqAAUzdfUx1ar7KCX+yNYLQAWAu8JpKTqtD4haamr1pCWpC+AwzQMfmvPOzRF0PeKQEHGWa1Oz3uy76c5xB9upYMiB+P0qYYeSFYJ51W4gs52bt6DyQfmpfZuwwVodd4ABczL9c5+OI5pW3VlFhlz8YbXKxMlJxY1uc=
