name: 发布到 oss

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        if: contains(github.event.head_commit.message, 'docs')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: 安装依赖
              run: npm install

            - name: 构建项目
              run: npm run docs:build

            - name: 启用 oss-util 工具
              uses: manyuanrong/setup-ossutil@v3.0
              with:
                  endpoint: 'oss-cn-hangzhou.aliyuncs.com'
                  access-key-id: ${{ secrets.AccessKeyId }}
                  access-key-secret: ${{ secrets.AccessKeySecret }}

            - name: 项目部署 - docs
              # https://help.aliyun.com/zh/oss/developer-reference/rm?spm=a2c4g.11186623.0.0.39f646afKK0HiH
              # 需要考虑先 rm 再 cp 否则文件会一直累加 （我们不需要版本控制，直接覆盖式发布即可）
              run: ossutil cp -rf ./docs/.vitepress/dist oss://90s/
