name: 发布到 oss

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        if: contains(github.event.head_commit.message, 'publish')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: 安装依赖
              run: npm install

            - name: 构建项目
              run: npm run build

            - name: 启用 oss-util 工具
              uses: manyuanrong/setup-ossutil@v3.0
              with:
                  endpoint: 'oss-cn-hangzhou.aliyuncs.com'
                  access-key-id: ${{ secrets.AccessKeyId }}
                  access-key-secret: ${{ secrets.AccessKeySecret }}

            # https://help.aliyun.com/zh/oss/developer-reference/
            # 对于文档系统我们经常修改的是文本内容，如果每次发布都全量推送所有资源（图片视频等）
            # 会降低上传效率，所以如果要更新资源需要明确的声明 'publish:all'
            # 既然是全量发布，那么可以对之前的文件夹进行一次删除，避免历史文件的冗余
            - name: 项目部署 - 更新文档和资源
              if: contains(github.event.head_commit.message, 'publish:all')
              run: |
                  ossutil rm oss://90s/article/ -rf
                  ossutil rm oss://90s/work/ -rf
                  ossutil rm oss://90s/assets/ -rf
                  ossutil cp -rf ./docs/.vitepress/dist oss://90s/

            - name: 项目部署 - 更新文档(排除了图片和视频等资源)
              if: contains(github.event.head_commit.message, 'publish:docs')
              run: ossutil cp -rf ./docs/.vitepress/dist oss://90s/ --exclude *.jpeg --exclude *.mov --exclude *.png
